name: Deploy to Google Cloud VM

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu klonla
      uses: actions/checkout@v3

    - name: SSH için anahtarları ayarla
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 34.34.178.121 >> ~/.ssh/known_hosts

    - name: SSH ile deploy scriptini çalıştır
      run: |
        ssh -i ~/.ssh/id_ed25519 ubuntu@34.34.178.121 "bash /home/ubuntu/deploy.sh"
